nelmio_api_doc:
    documentation:
        info:
            title: CMH Practical Test
            description: Horses REST API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc)
            - ^/horses
